meta <- data.frame(
    Title = c("Race interaction models developed on TCGA-PRAD cohort",
              "Race interaction models developed on TCGA-KIRC cohort",
              "Race interaction models developed on TCGA-HNSC cohort",
              "Race interaction models developed on TCGA-LUAD cohort",
              "Race interaction models developed on TCGA-UCEC cohort",
              "Race interaction models developed on TCGA-BRCA cohort",
              "Race interaction models developed on TCGA-KIRP cohort",
              "Race interaction models developed on TCGA-COAD cohort",
              "African American specific models developed on TCGA-BRCA cohort",
              "African American specific models developed on TCGA-KIRC cohort",
              "African American specific models developed on TCGA-HNSC cohort",
              "African American specific models developed on TCGA-LUAD cohort",
              "African American specific models developed on TCGA-UCEC cohort",
              "African American specific models developed on TCGA-KIRP cohort",
              "African American specific models developed on TCGA-COAD cohort",
              "African American specific models developed on TCGA-PRAD cohort",
              "European American specific models developed on TCGA-ACC cohort",
              "European American specific models developed on TCGA-UVM cohort",
              "European American specific models developed on TCGA-UCS cohort",
              "European American specific models developed on TCGA-THYM cohort",
              "European American specific models developed on TCGA-THCA cohort",
              "European American specific models developed on TCGA-TGCT cohort",
              "European American specific models developed on TCGA-STAD cohort",
              "European American specific models developed on TCGA-SKCM cohort",
              "European American specific models developed on TCGA-SARC cohort",
              "European American specific models developed on TCGA-READ cohort",
              "European American specific models developed on TCGA-PCPG cohort",
              "European American specific models developed on TCGA-PAAD cohort",
              "European American specific models developed on TCGA-MESO cohort",
              "European American specific models developed on TCGA-LUSC cohort",
              "European American specific models developed on TCGA-LIHC cohort",
              "European American specific models developed on TCGA-LGG cohort",
              "European American specific models developed on TCGA-KICH cohort",
              "European American specific models developed on TCGA-LAML cohort",
              "European American specific models developed on TCGA-GBM cohort",
              "European American specific models developed on TCGA-CESC cohort",
              "European American specific models developed on TCGA-BLCA cohort",
              "European American specific models developed on TCGA-ESCA cohort",
              "European American specific models developed on TCGA-KIRC cohort",
              "European American specific models developed on TCGA-LUAD cohort",
              "European American specific models developed on TCGA-UCEC cohort",
              "European American specific models developed on TCGA-BRCA cohort",
              "European American specific models developed on TCGA-KIRP cohort",
              "European American specific models developed on TCGA-COAD cohort",
              "European American specific models developed on TCGA-PRAD cohort",
              "European American specific models developed on TCGA-HNSC cohort"),
    Description = c(paste0("Race interaction models constructed on TCGA-PRAD cohort",
                           "consisting of models for 25,034 genes"),
                    paste0("Race interaction models constructed on TCGA-KIRC cohort",
                           "consisting of models for 25,007 genes"),
                    paste0("Race interaction models constructed on TCGA-HNSC cohort",
                           "consisting of models for 23,306 genes"),
                    paste0("Race interaction models constructed on TCGA-LUAD cohort",
                           "consisting of models for 24,850 genes"),
                    paste0("Race interaction models constructed on TCGA-UCEC cohort",
                           "consisting of models for 22,927 genes"),
                    paste0("Race interaction models constructed on TCGA-BRCA cohort",
                           "consisting of models for 24,832 genes"),
                    paste0("Race interaction models constructed on TCGA-KIRP cohort",
                           "consisting of models for 23,659 genes"),
                    paste0("Race interaction models constructed on TCGA-COAD cohort",
                           "consisting of models for 23,034 genes"),
                    paste0("African American specific models developed on TCGA-BRCA cohort",
                           "consisting of models for 17,632 genes"),
                    paste0("African American specific models developed on TCGA-KIRC cohort",
                           "consisting of models for 14,301 genes"),
                    paste0("African American specific models developed on TCGA-HNSC cohort",
                           "consisting of models for 12,538 genes"),
                    paste0("African American specific models developed on TCGA-LUAD cohort",
                           "consisting of models for 14,965 genes"),
                    paste0("African American specific models developed on TCGA-UCEC cohort",
                           "consisting of models for 20,919 genes"),
                    paste0("African American specific models developed on TCGA-KIRP cohort",
                           "consisting of models for 16,296 genes"),
                    paste0("African American specific models developed on TCGA-COAD cohort",
                           "consisting of models for 16,772 genes"),
                    paste0("African American specific models developed on TCGA-PRAD cohort",
                           "consisting of models for 17,882 genes"),
                    paste0("European American specific models developed on TCGA-ACC cohort",
                           "consisting of models for 17,214 genes"),
                    paste0("European American specific models developed on TCGA-UVM cohort",
                           "consisting of models for 14,126 genes"),
                    paste0("European American specific models developed on TCGA-UCS cohort",
                           "consisting of models for 10,879 genes"),
                    paste0("European American specific models developed on TCGA-THYM cohort",
                           "consisting of models for 21,917 genes"),
                    paste0("European American specific models developed on TCGA-THCA cohort",
                           "consisting of models for 23,180 genes"),
                    paste0("European American specific models developed on TCGA-TGCT cohort",
                           "consisting of models for 24,709 genes"),
                    paste0("European American specific models developed on TCGA-STAD cohort",
                           "consisting of models for 27,882 genes"),
                    paste0("European American specific models developed on TCGA-SKCM cohort",
                           "consisting of models for 21,767 genes"),
                    paste0("European American specific models developed on TCGA-SARC cohort",
                           "consisting of models for 20,768 genes"),
                    paste0("European American specific models developed on TCGA-READ cohort",
                           "consisting of models for 21,142 genes"),
                    paste0("European American specific models developed on TCGA-PCPG cohort",
                           "consisting of models for 21,012 genes"),
                    paste0("European American specific models developed on TCGA-PAAD cohort",
                           "consisting of models for 23,752 genes"),
                    paste0("European American specific models developed on TCGA-MESO cohort",
                           "consisting of models for 21,020 genes"),
                    paste0("European American specific models developed on TCGA-LUSC cohort",
                           "consisting of models for 24,284 genes"),
                    paste0("European American specific models developed on TCGA-LIHC cohort",
                           "consisting of models for 20,006 genes"),
                    paste0("European American specific models developed on TCGA-LGG cohort",
                           "consisting of models for 25,170 genes"),
                    paste0("European American specific models developed on TCGA-KICH cohort",
                           "consisting of models for 16,140 genes"),
                    paste0("European American specific models developed on TCGA-LAML cohort",
                           "consisting of models for 24,423 genes"),
                    paste0("European American specific models developed on TCGA-GBM cohort",
                           "consisting of models for 18,015 genes"),
                    paste0("European American specific models developed on TCGA-CESC cohort",
                           "consisting of models for 21,806 genes"),
                    paste0("European American specific models developed on TCGA-BLCA cohort",
                           "consisting of models for 21,291 genes"),
                    paste0("European American specific models developed on TCGA-ESCA cohort",
                           "consisting of models for 27,797 genes"),
                    paste0("European American specific models developed on TCGA-KIRC cohort",
                           "consisting of models for 23,459 genes"),
                    paste0("European American specific models developed on TCGA-LUAD cohort",
                           "consisting of models for 22,992 genes"),
                    paste0("European American specific models developed on TCGA-UCEC cohort",
                           "consisting of models for 21,420 genes"),
                    paste0("European American specific models developed on TCGA-BRCA cohort",
                           "consisting of models for 22,440 genes"),
                    paste0("European American specific models developed on TCGA-KIRP cohort",
                           "consisting of models for 22,100 genes"),
                    paste0("European American specific models developed on TCGA-COAD cohort",
                           "consisting of models for 21,822 genes"),
                    paste0("European American specific models developed on TCGA-PRAD cohort",
                           "consisting of models for 23,813 genes"),
                    paste0("European American specific models developed on TCGA-HNSC cohort",
                           "consisting of models for 21,496 genes")),
    BiocVersion = "3.13",
    Genome = rep("hg38", 46),
    SourceType = rep("RDA", 46),
    SourceVersion = "Apr 27 2021",
    Species = "Homo sapiens",
    TaxonomyId = 9606,
    SourceUrl = "https://bioconductor.org/packages/release/bioc/html/TCGAbiolinks.html",
    DataProvider = "TCGAbiolinks",
    Coordinate_1_based = NA,
    Maintainer = "Ian Loveless ilovele1@hfhs.org",
    RDataClass = rep("list", 46),
    DispatchClass = c(rep("Rda",46)),
    RDataPath = c("EpiXprSData/PRAD.Rda", "EpiXprSData/KIRC.Rda",
                  "EpiXprSData/HNSC.Rda", "EpiXprSData/LUAD.Rda", "EpiXprSData/UCEC.Rda",
                  "EpiXprSData/BRCA.Rda", "EpiXprSData/KIRP.Rda", "EpiXprSData/COAD.Rda",
                  "EpiXprSData/BRCAaa.Rda", "EpiXprSData/KIRCaa.Rda", "EpiXprSData/HNSCaa.Rda",
                  "EpiXprSData/LUADaa.Rda", "EpiXprSData/UCECaa.Rda", "EpiXprSData/KIRPaa.Rda",
                  "EpiXprSData/COADaa.Rda", "EpiXprSData/PRADaa.Rda", "EpiXprSData/ACCea.Rda",
                  "EpiXprSData/UVMea.Rda", "EpiXprSData/UCSea.Rda", "EpiXprSData/THYMea.Rda",
                  "EpiXprSData/THCAea.Rda", "EpiXprSData/TGCTea.Rda", "EpiXprSData/STADea.Rda",
                  "EpiXprSData/SKCMea.Rda", "EpiXprSData/SARCea.Rda", "EpiXprSData/READea.Rda",
                  "EpiXprSData/PCPGea.Rda", "EpiXprSData/PAADea.Rda", "EpiXprSData/MESOea.Rda",
                  "EpiXprSData/LUSCea.Rda", "EpiXprSData/LIHCea.Rda", "EpiXprSData/LGG.Rda",
                  "EpiXprSData/KICHea.Rda", "EpiXprSData/LAMLea.Rda", "EpiXprSData/GBMea.Rda",
                  "EpiXprSData/CESCea.Rda", "EpiXprSData/BLCAea.Rda", "EpiXprSData/ESCAea.Rda",
                  "EpiXprSData/KIRCea.Rda", "EpiXprSData/LUADea.Rda", "EpiXprSData/UCECea.Rda",
                  "EpiXprSData/BRCAea.Rda", "EpiXprSData/KIRPea.Rda", "EpiXprSData/COADea.Rda",
                  "EpiXprSData/PRADea.Rda", "EpiXprSData/HNSCea.Rda"),
    Tags = "",
    Notes = rep(paste0("Original Release"),46)
)

write.csv(meta, file="inst/extdata/metadata.csv", row.names=FALSE)
